---
peroperative_seq_functions_shorter:
  refgenome: "/home/docker/refGenome/chm13v2.0.fa"
  guppy: "/opt/ont-guppy/"
  probes: "probelocs_chm13.bed"
  model: "/opt/sturgeon/sturgeon/include/models/model.zip"
  modelname: "model"
